services:
  fastapi:
    container_name: neural-fastapi
    build: ..
    command: uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ..:/code
    ports:
      - "8000:8000"
    networks:
      - work_match_neural_network

networks:
  work_match_neural_network:
    driver: bridge
