services:
    ollama:
        image: ollama/ollama
        container_name: ollama
        ports:
            - "11434:11434"
        networks:
            - work_match_neural_network
        volumes:
            - ollama:/root/.ollama
networks:
    work_match_neural_network:
        driver: bridge
volumes:
    ollama:
